pool:
  vmImage: Ubuntu 20.04
steps:
  - task: InstallMATLAB@0
    inputs:
      release: R2020b
  - task: RunMATLABCommand@0 
    inputs:
      command: "addpath(genpath('src')); cd('test'); results = runAllTests(); assertSuccess(results)"
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test/junit_test_results.xml'  